# High-Accuracy Bayesian Networks Configuration
# Optimized for maximum precision and comprehensive analysis

# Core Bayesian Engine Configuration
bayesian_engine:
  enable_temporal_modeling: true
  enable_hierarchical_modeling: true
  enable_causal_analysis: true
  inference_method: "variational"
  temporal_window_size: 20             # Extended window for better analysis
  max_inference_time: 10.0             # Allow longer processing time
  uncertainty_threshold: 0.05          # Strict uncertainty requirements

# Temporal Modeling Configuration
temporal_modeling:
  window_size: 20                      # Large window for comprehensive analysis
  max_history: 50                      # Extended history tracking
  consistency_thresholds:
    delta_fr_revised: 0.3              # Fine-grained thresholds
    delta_ft_revised: 0.015
    delta_fv_revised: 0.2
  transition_probabilities:
    same_state: 0.6                    # More sensitive to changes
    adjacent_state: 0.35
    distant_state: 0.05

# Hierarchical Modeling Configuration
hierarchical_modeling:
  user_weight: 0.35                    # Balanced multi-level analysis
  session_weight: 0.35
  audio_weight: 0.3
  adaptation_rate: 0.15                # Higher adaptation for personalization
  min_samples_for_adaptation: 3        # Quick adaptation
  user_risk_thresholds:
    low_risk: 0.85                     # Strict risk assessment
    medium_risk: 0.5

# Causal Analysis Configuration
causal_analysis:
  enable_interventions: true
  enable_counterfactuals: true
  causal_effects:
    synthesis_algorithm:
      delta_fr_revised: 0.85           # Enhanced causal modeling
      delta_ft_revised: 0.35
      delta_fv_revised: 0.45
      authenticity: -0.95
    algorithm_artifacts:
      delta_fr_revised: 0.75
      delta_ft_revised: 0.25
      delta_fv_revised: 0.35
      authenticity: -0.85
    temporal_inconsistencies:
      delta_fr_revised: 0.65
      delta_ft_revised: 0.55
      delta_fv_revised: 0.45
      authenticity: -0.75
    vocoder_effects:
      delta_fr_revised: 0.55
      delta_ft_revised: 0.45
      delta_fv_revised: 0.65
      authenticity: -0.65

# Inference Engine Configuration
inference:
  variational:
    max_iterations: 2000               # Extended iterations for convergence
    tolerance: 1e-8                    # Very strict tolerance
    learning_rate: 0.005               # Conservative learning rate
    use_gpu: true
    structured: true                   # Use structured variational inference

# Feature Discretization Configuration
discretization:
  delta_fr_thresholds: [6.2, 7.2]     # Fine-grained discretization
  delta_ft_thresholds: [0.055, 0.075]
  delta_fv_thresholds: [0.9, 1.3]
  confidence_thresholds: [0.8, 0.9, 0.97]  # High confidence requirements

# Performance Configuration
performance:
  enable_gpu_acceleration: true
  batch_inference: true                # Efficient batch processing
  cache_inference_results: true       # Cache for consistency
  parallel_user_processing: true      # Parallel processing where safe
  max_concurrent_inferences: 8        # High parallelism

# Validation and Testing Configuration
validation:
  cross_validation_folds: 10           # Extensive validation
  test_split_ratio: 0.25
  enable_model_validation: true

# Privacy and Data Management
privacy:
  data_retention_days: 90              # Extended retention for learning
  anonymize_user_data: true
  enable_user_deletion: true
  audit_logging: true

# Logging Configuration
logging:
  level: "DEBUG"                       # Comprehensive logging
  enable_performance_logging: true
  enable_inference_logging: true      # Detailed inference logs
  log_file: "bayesian_high_accuracy.log" 